org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1


mod_id=meatwo310
mod_name=Meatwo310
mod_license=GPL-3.0
mod_version=3.1.0-a
mod_group_id=com.dousiyo.meatwo310
mod_authors=Meatwo310, uribo_ya
mod_description=Description dousiyo
